### ISSUE TITLE
Multiple version specifiers do not seem to be taken into account

### ISSUE THREAD

**Issue by christophehenry** [meanmail-dev/requirements#77]
**Describe the bug**
(This may be a broader issue with version specification, though)
The Requirements plugin keeps suggesting that I upgrade Django to version 4.0.1, no matter what version specifiers I put in the `requirements.txt` file. Here are the version specifiers I tried:

```txt
Djang==3.2.11  # Legit
Django==3.2.11,<4
Django==3.2.11,<4.0
Django==3.2.11,<4.0.*
Django==3.2.11,<4.0,!=4.0.1
Django!=4.0.1,==3.2.11
Django<4
Django<4.0
```

Only if I put `Django!=4.0.1` Requirements proposes me Django 4.0.

**To Reproduce**
1. Create a `requirements.txt`
2. Try any of the dependencies specifiers above
3. Requirements proposes to install Django 4.0.1 (or whatever last version of Django 4.0 is)

**Expected behavior**
Requirements should not propose to updrade to Django 4.0 when this version was excluded by a specifier

**Screenshots**
![Screenshot_20220124_112700](https://user-images.githubusercontent.com/22097904/150798380-a856e18b-f650-4dfa-8336-e0ddf5713729.png)

**IDE:**
 - OS: Linux (Fedora 35)
 - Product: PyCharm professionnal edition
 - Version PY-213.6461.77, built on December 28, 2021
 - JRE Version: 11.0.13+7-b1751.21 amd64 OpenJDK 64-Bit Server VM by JetBrains s.r.o.
 - Project SDK: Python 3.10

**Plugin:**
 - Version 2022.2-2021.3

**Comment by meanmail** [comment]
@christophehenry Fixed in 2022.3

**Comment by christophehenry** [comment]
This issue still reproduces here with version 2022.3-2021.3 and the exact same specifiers.
